/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ToolsImport } from './routes/tools'
import { Route as PracticesImport } from './routes/practices'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ToolsRoute = ToolsImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRoute,
} as any)

const PracticesRoute = PracticesImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/practices': {
      id: '/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesImport
      parentRoute: typeof rootRoute
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practices': typeof PracticesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practices': typeof PracticesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/practices': typeof PracticesRoute
  '/tools': typeof ToolsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/practices' | '/tools'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/practices' | '/tools'
  id: '__root__' | '/' | '/practices' | '/tools'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticesRoute: typeof PracticesRoute
  ToolsRoute: typeof ToolsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticesRoute: PracticesRoute,
  ToolsRoute: ToolsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/practices",
        "/tools"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/practices": {
      "filePath": "practices.tsx"
    },
    "/tools": {
      "filePath": "tools.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
